#------------------------------------------------------------------------------------------------------------------------------------
#Dockerfile for React Application
#------------------------------------------------------------------------------------------------------------------------------------   
#alpine -> Lightweight image as dependencies are getting installed and source code is mounted
FROM alpine
WORKDIR /app
#Install npm
RUN apk add --no-cache npm